[info]
relay_url = "wss://relay.equaliser.app/"
name = "Equaliser Standard Relay"
description = "Open NOSTR relay for Equaliser user data caching"

[database]
data_directory = "/usr/src/app/db"

[network]
port = 8080
address = "0.0.0.0"

[limits]
messages_per_sec = 5
max_event_bytes = 131072
max_ws_message_bytes = 131072
